Update modified_sklearn_BayesianRidge.py
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[38], line 1
----> 1 exp = explainer.explain_instance(test[i], rf.predict_proba,#num_features=13,
      2                                  model_regressor= BayesianRidge_inf_prior(),
      3                                  num_samples=50)#'non_Bay' 'Bay_non_info_prior' 'Bay_info_prior'
      5 exp.show_in_notebook(show_table=True)

File /opt/conda/lib/python3.10/site-packages/lime/lime_tabular.py:452, in LimeTabularExplainer.explain_instance(self, data_row, predict_fn, labels, top_labels, num_features, num_samples, distance_metric, model_regressor)
    448     labels = [0]
    449 for label in labels:
    450     (ret_exp.intercept[label],
    451      ret_exp.local_exp[label],
--> 452      ret_exp.score, ret_exp.local_pred) = self.base.explain_instance_with_data(
    453             scaled_data,
    454             yss,
    455             distances,
    456             label,
    457             num_features,
    458             model_regressor=model_regressor,
    459             feature_selection=self.feature_selection)
    461 if self.mode == "regression":
    462     ret_exp.intercept[1] = ret_exp.intercept[0]

File /opt/conda/lib/python3.10/site-packages/lime/lime_base.py:192, in LimeBase.explain_instance_with_data(self, neighborhood_data, neighborhood_labels, distances, label, num_features, feature_selection, model_regressor)
    189     model_regressor = Ridge(alpha=1, fit_intercept=True,
    190                             random_state=self.random_state)
    191 easy_model = model_regressor
--> 192 easy_model.fit(neighborhood_data[:, used_features],
    193                labels_column, sample_weight=weights)
    194 prediction_score = easy_model.score(
    195     neighborhood_data[:, used_features],
    196     labels_column, sample_weight=weights)
    198 local_pred = easy_model.predict(neighborhood_data[0, used_features].reshape(1, -1))

File /opt/conda/lib/python3.10/site-packages/sklearn/linear_model/modified_sklearn_BayesianRidge.py:212, in BayesianRidge_inf_prior.fit(self, X, y, sample_weight)
    208 if sample_weight is not None:
    209     sample_weight = _check_sample_weight(sample_weight, X,
    210                                          dtype=X.dtype)
--> 212 X, y, X_offset_, y_offset_, X_scale_ = self._preprocess_data(
    213     X, y, self.fit_intercept, self.normalize, self.copy_X,
    214     sample_weight=sample_weight)
    216 if sample_weight is not None:
    217     # Sample weight can be implemented via a simple rescaling.
    218     X, y = _rescale_data(X, y, sample_weight)

AttributeError: 'BayesianRidge_inf_prior' object has no attribute '_preprocess_data'


trying figure out the _preprocess_data part